/*
	This file was automatically created using a source code generator.
	Do not edit this file manually as all changes will be overwritten
	the next time the generator runs again.
*/



module cuboro.tables
{
	export class AdminSettingVO
	{
		public static ID_MAX_LENGTH = 128;
		public static ID_MAX_LENGTH_SECURE = 64;

		public static VALUE_MAX_LENGTH = 128;
		public static VALUE_MAX_LENGTH_SECURE = 64;
	}
}
