/*
	This file was automatically created using a source code generator.
	Do not edit this file manually as all changes will be overwritten
	the next time the generator runs again.
*/



/// <reference path="../../cuboro/tables/reportscommentvo.ts"/>
/// <reference path="../../cuboro/tables/trackvo.ts"/>
/// <reference path="../../cuboro/tables/uservo.ts"/>
/// <reference path="../../kr3m/types.ts"/>
//# !CLIENT
/// <reference path="../../kr3m/services/paramshelper.ts"/>
/// <reference path="../../kr3m/util/factory.ts"/>
//# /!CLIENT



module cuboro.tables
{
	export class CommentVO
	{
		public static COMMENT_MAX_LENGTH = 65535;
		public static COMMENT_MAX_LENGTH_SECURE = 32767;



		public comment:string; // text
		public createdWhen:Date = new Date(); // timestamp
		public id:number; // int unsigned
		public trackId:number; // int unsigned
		public userId:number; // bigint unsigned
//# !CLIENT



		public static isColumnName(name:string):boolean
		{
			return (["comment","createdWhen","id","trackId","userId"]).indexOf(name) >= 0;
		}



		public static getColumnNames():string[]
		{
			return ["comment","createdWhen","id","trackId","userId"];
		}



		/*
			Builds a proper cuboro.tables.CommentVO class object from
			a POD / JSON object.

			If this is not possible, because some required attributes
			are missing for example, null will be returned.
		*/
		public static buildFrom(raw:any):cuboro.tables.CommentVO
		{
			var helper = new kr3m.services.ParamsHelper(raw);
			if (!helper.validate({"comment":"string","createdWhen":"Date","id":"number","trackId":"number","userId":"number"}, {"createdWhen":"CURRENT_TIMESTAMP"}))
				return null;

			var foreignKeyNames = ["trackId","userId"];
			var vo = new cuboro.tables.CommentVO();
			var copyFields = ["comment","createdWhen","id","trackId","userId"];
			for (var i = 0; i < copyFields.length; ++i)
			{
				vo[copyFields[i]] = raw[copyFields[i]];
				if (!vo[copyFields[i]] && kr3m.util.Util.contains(foreignKeyNames, copyFields[i]))
					vo[copyFields[i]] = null;
			}
			return vo;
		}



		public constructor(rawData?:any)
		{
			if (rawData)
			{
				for (var i in rawData)
				{
					if (cuboro.tables.CommentVO.isColumnName(i))
						this[i] = rawData[i];
				}
			}
		}



		private wrapErrorCallback(
			errorCallback:ErrorCallback,
			functionName:string):ErrorCallback
		{
			if (!errorCallback)
				return errorCallback;

			var newCallback = (errorMessage) =>
			{
				errorCallback("cuboro.tables.CommentVO." + functionName + " - " + errorMessage);
			}
			return newCallback;
		}



		/*
			Will be called after the class was created and filled
			with content from the database.
		*/
		public postLoad():void
		{
			// can be overwritten in derived classes
		}



		/*
			Will be called before the class' content will be
			written into the database.
		*/
		public preStore():void
		{
			// can be overwritten in derived classes
		}



		/*
			Will be called after the class' content was
			written into the database.
		*/
		public postStore():void
		{
			// can be overwritten in derived classes
		}



		public insert(
			callback?:(insertedId:number) => void,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "insert");
			this.preStore();
			db.insert("comments", this, (insertedId:number) =>
			{
				this.id = insertedId;
				this.postStore();
				callback && callback(insertedId);
			}, errorCallback);
		}



		public upsert(
			callback?:(insertedId:number) => void,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "upsert");
			this.preStore();
			db.upsert("comments", this, (insertedId:number) =>
			{
				this.id = insertedId || this.id;
				this.postStore();
				callback && callback(insertedId);
			}, null, errorCallback);
		}



		public update(
			callback?:Callback,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "update");
			this.preStore();
			db.update("comments", this, () =>
			{
				this.postStore();
				callback && callback();
			}, "id", errorCallback);
		}



		public delete(
			callback?:Callback,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "delete");
			var where = db.escape("id = ?", [this.id]);
			db.deleteBatch("comments", where, callback, errorCallback);
		}



		public getTrack(
			callback:CB<cuboro.tables.TrackVO>,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "getTrack");
			var sql = "SELECT * FROM `tracks` WHERE `id` = ? LIMIT 0,1";
			sql = db.escape(sql, [this.trackId]);
			db.fetchRow(sql, (data) =>
			{
				if (!data)
					return callback(undefined);

				data.__proto__ = kr3m.util.Factory.getInstance().map(cuboro.tables.TrackVO).prototype;
				data.postLoad();
				callback(data);
			}, errorCallback);
		}



		public getUser(
			callback:CB<cuboro.tables.UserVO>,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "getUser");
			var sql = "SELECT * FROM `users` WHERE `id` = ? LIMIT 0,1";
			sql = db.escape(sql, [this.userId]);
			db.fetchRow(sql, (data) =>
			{
				if (!data)
					return callback(undefined);

				data.__proto__ = kr3m.util.Factory.getInstance().map(cuboro.tables.UserVO).prototype;
				data.postLoad();
				callback(data);
			}, errorCallback);
		}



		public getReportscomment(
			where:string|{[colName:string]:any},
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.ReportscommentVO[]>,
			errorCallback:ErrorCallback):void;

		public getReportscomment(
			where:string|{[colName:string]:any},
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.ReportscommentVO[]>):void;

		public getReportscomment(
			where:string|{[colName:string]:any},
			callback:CB<cuboro.tables.ReportscommentVO[]>,
			errorCallback:ErrorCallback):void;

		public getReportscomment(
			where:string|{[colName:string]:any},
			callback:CB<cuboro.tables.ReportscommentVO[]>):void;

		public getReportscomment(
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.ReportscommentVO[]>,
			errorCallback:ErrorCallback):void;

		public getReportscomment(
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.ReportscommentVO[]>):void;

		public getReportscomment(
			callback:CB<cuboro.tables.ReportscommentVO[]>,
			errorCallback:ErrorCallback):void;

		public getReportscomment(
			callback:CB<cuboro.tables.ReportscommentVO[]>):void;

		public getReportscomment():void
		{
			var u = kr3m.util.Util;


			var whereObj = <{[colName:string]:any}> u.getFirstOfType(arguments, "object", 0, 0);
			var whereString = whereObj ? db.where(whereObj) : <string> u.getFirstOfType(arguments, "string", 0, 0);
			var where = whereString ? " AND (" + whereString.replace(/\bWHERE\b/i, "") + ") " : "";

			var offset = <number> u.getFirstOfType(arguments, "number", 0, 0);
			var limit = <number> u.getFirstOfType(arguments, "number", 0, 1);
			var limits = (offset !== undefined && limit !== undefined) ? db.escape(" LIMIT ?, ?", [offset, limit]) : "";

			var callback = <CB<cuboro.tables.ReportscommentVO[]>> u.getFirstOfType(arguments, "function", 0, 0);
			var errorCallback = <ErrorCallback> u.getFirstOfType(arguments, "function", 0, 1);
			errorCallback = this.wrapErrorCallback(errorCallback, "getReportscomment");

			var sql = "SELECT * FROM `reportscomment` WHERE `commentId` = ? " + where + limits;
			sql = db.escape(sql, [this.id]);
			db.fetchAll(sql, (rows) =>
			{
				for (var i = 0; i < rows.length; ++i)
				{
					rows[i].__proto__ = kr3m.util.Factory.getInstance().map(cuboro.tables.ReportscommentVO).prototype;
					rows[i].postLoad();
				}
				callback(rows);
			}, errorCallback);
		}



		public getReportscommentByUserId(
			userId:number,
			callback:CB<cuboro.tables.ReportscommentVO>,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "getReportscommentByUserId");
			var sql = "SELECT * FROM `reportscomment` WHERE `commentId` = ? AND `userId` = ? LIMIT 0,1";
			sql = db.escape(sql, [this.id, userId]);
			db.fetchRow(sql, (data) =>
			{
				if (!data)
					return callback(undefined);

				data.__proto__ = kr3m.util.Factory.getInstance().map(cuboro.tables.ReportscommentVO).prototype;
				data.postLoad();
				callback(data);
			}, errorCallback);
		}

//# /!CLIENT
	}
}
