/*
	This file was automatically created using a source code generator.
	Do not edit this file manually as all changes will be overwritten
	the next time the generator runs again.
*/



module cuboro.tables
{
	export class CommentVO
	{
		public static COMMENT_MAX_LENGTH = 65535;
		public static COMMENT_MAX_LENGTH_SECURE = 32767;
	}
}
