/*
	This file was automatically created using a source code generator.
	Do not edit this file manually as all changes will be overwritten
	the next time the generator runs again.
*/



module cuboro.tables
{
	export class CompetitionVO
	{
		public static NAME_INTERNAL_MAX_LENGTH = 128;
		public static NAME_INTERNAL_MAX_LENGTH_SECURE = 64;

		public static REGION_ID_MAX_LENGTH = 16;
		public static REGION_ID_MAX_LENGTH_SECURE = 8;
	}
}
