/*
	This file was automatically created using a source code generator.
	Do not edit this file manually as all changes will be overwritten
	the next time the generator runs again.
*/



module cuboro.tables
{
	export class LocalizationVO
	{
		public static FIELD_MAX_LENGTH = 32;
		public static FIELD_MAX_LENGTH_SECURE = 16;

		public static ITEM_TYPE_MAX_LENGTH = 32;
		public static ITEM_TYPE_MAX_LENGTH_SECURE = 16;

		public static LOCALE_MAX_LENGTH = 4;
		public static LOCALE_MAX_LENGTH_SECURE = 2;

		public static TEXT_MAX_LENGTH = 65535;
		public static TEXT_MAX_LENGTH_SECURE = 32767;
	}
}
