/*
	This file was automatically created using a source code generator.
	Do not edit this file manually as all changes will be overwritten
	the next time the generator runs again.
*/



module cuboro.tables
{
	export class RegionVariantVO
	{
		public static ID_MAX_LENGTH = 32;
		public static ID_MAX_LENGTH_SECURE = 16;

		public static LANGUAGE_IDS_MAX_LENGTH = 256;
		public static LANGUAGE_IDS_MAX_LENGTH_SECURE = 128;

		public static REGION_ID_MAX_LENGTH = 2;
		public static REGION_ID_MAX_LENGTH_SECURE = 1;
	}
}
