/*
	This file was automatically created using a source code generator.
	Do not edit this file manually as all changes will be overwritten
	the next time the generator runs again.
*/



/// <reference path="../../cuboro/tables/regionvariantvo.ts"/>
/// <reference path="../../kr3m/types.ts"/>
//# !CLIENT
/// <reference path="../../kr3m/services/paramshelper.ts"/>
/// <reference path="../../kr3m/util/factory.ts"/>
//# /!CLIENT



module cuboro.tables
{
	export class RegionDomainVO
	{
		public static NAME_MAX_LENGTH = 200;
		public static NAME_MAX_LENGTH_SECURE = 100;

		public static REGION_ID_MAX_LENGTH = 32;
		public static REGION_ID_MAX_LENGTH_SECURE = 16;



		public name:string; // varchar(200)
		public regionId:string; // varchar(32)
//# !CLIENT



		public static isColumnName(name:string):boolean
		{
			return (["name","regionId"]).indexOf(name) >= 0;
		}



		public static getColumnNames():string[]
		{
			return ["name","regionId"];
		}



		/*
			Builds a proper cuboro.tables.RegionDomainVO class object from
			a POD / JSON object.

			If this is not possible, because some required attributes
			are missing for example, null will be returned.
		*/
		public static buildFrom(raw:any):cuboro.tables.RegionDomainVO
		{
			var helper = new kr3m.services.ParamsHelper(raw);
			if (!helper.validate({"name":"string","regionId":"string"}, {}))
				return null;

			var foreignKeyNames = ["regionId"];
			var vo = new cuboro.tables.RegionDomainVO();
			var copyFields = ["name","regionId"];
			for (var i = 0; i < copyFields.length; ++i)
			{
				vo[copyFields[i]] = raw[copyFields[i]];
				if (!vo[copyFields[i]] && kr3m.util.Util.contains(foreignKeyNames, copyFields[i]))
					vo[copyFields[i]] = null;
			}
			return vo;
		}



		public constructor(rawData?:any)
		{
			if (rawData)
			{
				for (var i in rawData)
				{
					if (cuboro.tables.RegionDomainVO.isColumnName(i))
						this[i] = rawData[i];
				}
			}
		}



		private wrapErrorCallback(
			errorCallback:ErrorCallback,
			functionName:string):ErrorCallback
		{
			if (!errorCallback)
				return errorCallback;

			var newCallback = (errorMessage) =>
			{
				errorCallback("cuboro.tables.RegionDomainVO." + functionName + " - " + errorMessage);
			}
			return newCallback;
		}



		/*
			Will be called after the class was created and filled
			with content from the database.
		*/
		public postLoad():void
		{
			// can be overwritten in derived classes
		}



		/*
			Will be called before the class' content will be
			written into the database.
		*/
		public preStore():void
		{
			// can be overwritten in derived classes
		}



		/*
			Will be called after the class' content was
			written into the database.
		*/
		public postStore():void
		{
			// can be overwritten in derived classes
		}



		protected checkName(
			callback:(wasGenerated:boolean) => void,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "checkName");
			if (this.name)
				return callback(false);

			kr3m.async.Loop.loop((loopDone) =>
			{
				kr3m.util.Rand.getSecureString(200, null, (secureValue) =>
				{
					this.name = secureValue;
					db.fetchOne(db.escape("SELECT name FROM region_domains WHERE name = ? LIMIT 0,1;", [this.name]), dummy => loopDone(!!dummy), errorCallback);
				});
			}, () => callback(true));
		}



		public insert(
			callback?:Callback,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "insert");
			var retries = 3;
			kr3m.async.Loop.loop((loopDone) =>
			{
				this.checkName((wasGenerated) =>
				{
					this.preStore();
					db.insert("region_domains", this, () =>
					{
						this.postStore();
						callback && callback();
					}, (errorMessage) =>
					{
						if (!wasGenerated || retries <= 0 || errorMessage.indexOf("ER_DUP_ENTRY") < 0)
						{
							if (errorCallback)
								return errorCallback(errorMessage);

							logError(errorMessage);
							return callback && callback();
						}

						logWarning(errorMessage);
						logWarning("retrying");
						--retries;
						loopDone(true);
					});
				});
			});
		}



		public upsert(
			callback?:Callback,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "upsert");
			var retries = 3;
			kr3m.async.Loop.loop((loopDone) =>
			{
				this.checkName((wasGenerated) =>
				{
					this.preStore();
					db.upsert("region_domains", this, () =>
					{
						this.postStore();
						callback && callback();
					}, null, (errorMessage) =>
					{
						if (!wasGenerated || retries <= 0 || errorMessage.indexOf("ER_DUP_ENTRY") < 0)
						{
							if (errorCallback)
								return errorCallback(errorMessage);

							logError(errorMessage);
							return callback && callback();
						}

						logWarning(errorMessage);
						logWarning("retrying");
						--retries;
						loopDone(true);
					});
				});
			});
		}



		public update(
			callback?:Callback,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "update");
			this.preStore();
			db.update("region_domains", this, () =>
			{
				this.postStore();
				callback && callback();
			}, "name", errorCallback);
		}



		public delete(
			callback?:Callback,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "delete");
			var where = db.escape("name = ?", [this.name]);
			db.deleteBatch("region_domains", where, callback, errorCallback);
		}



		public getRegion(
			callback:CB<cuboro.tables.RegionVariantVO>,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "getRegion");
			var sql = "SELECT * FROM `region_variants` WHERE `id` = ? LIMIT 0,1";
			sql = db.escape(sql, [this.regionId]);
			db.fetchRow(sql, (data) =>
			{
				if (!data)
					return callback(undefined);

				data.__proto__ = kr3m.util.Factory.getInstance().map(cuboro.tables.RegionVariantVO).prototype;
				data.postLoad();
				callback(data);
			}, errorCallback);
		}

//# /!CLIENT
	}
}
