/*
	This file was automatically created using a source code generator.
	Do not edit this file manually as all changes will be overwritten
	the next time the generator runs again.
*/



module cuboro.tables
{
	export class SessionVO
	{
		public static ID_MAX_LENGTH = 32;
		public static ID_MAX_LENGTH_SECURE = 16;

		public static VALUES_JSON_MAX_LENGTH = 65535;
		public static VALUES_JSON_MAX_LENGTH_SECURE = 32767;
	}
}
