/*
	This file was automatically created using a source code generator.
	Do not edit this file manually as all changes will be overwritten
	the next time the generator runs again.
*/



/// <reference path="../../cuboro/tables/commentvo.ts"/>
/// <reference path="../../cuboro/tables/competitionvo.ts"/>
/// <reference path="../../cuboro/tables/regionvariantvo.ts"/>
/// <reference path="../../cuboro/tables/uservo.ts"/>
/// <reference path="../../kr3m/types.ts"/>
//# !CLIENT
/// <reference path="../../kr3m/services/paramshelper.ts"/>
/// <reference path="../../kr3m/util/factory.ts"/>
//# /!CLIENT



module cuboro.tables
{
	export class TrackVO
	{
		public static DATA_MAX_LENGTH = 4294967295;
		public static DATA_MAX_LENGTH_SECURE = 2147483647;

		public static IMAGE_URL_MAX_LENGTH = 65535;
		public static IMAGE_URL_MAX_LENGTH_SECURE = 32767;

		public static NAME_MAX_LENGTH = 200;
		public static NAME_MAX_LENGTH_SECURE = 100;

		public static REGION_ID_MAX_LENGTH = 32;
		public static REGION_ID_MAX_LENGTH_SECURE = 16;



		public createdWhen:Date = new Date(); // timestamp
		public data:string; // longtext
		public id:number; // int unsigned
		public imageUrl:string; // text
		public isEducational:boolean = false;
		public isPublished:boolean = false;
		public lastSavedWhen:Date = new Date(); // timestamp
		public name:string; // varchar(200)
		public ownerId:number; // bigint unsigned
		public previousId:number = null; // int unsigned
		public regionId:string = "MAIN"; // varchar(32)
		public scoreTotal:number; // int unsigned
//# !CLIENT



		public static isColumnName(name:string):boolean
		{
			return (["createdWhen","data","id","imageUrl","isEducational","isPublished","lastSavedWhen","name","ownerId","previousId","regionId","scoreTotal"]).indexOf(name) >= 0;
		}



		public static getColumnNames():string[]
		{
			return ["createdWhen","data","id","imageUrl","isEducational","isPublished","lastSavedWhen","name","ownerId","previousId","regionId","scoreTotal"];
		}



		/*
			Builds a proper cuboro.tables.TrackVO class object from
			a POD / JSON object.

			If this is not possible, because some required attributes
			are missing for example, null will be returned.
		*/
		public static buildFrom(raw:any):cuboro.tables.TrackVO
		{
			var helper = new kr3m.services.ParamsHelper(raw);
			if (!helper.validate({"createdWhen":"Date","data":"string","id":"number","imageUrl":"string","isEducational":"boolean","isPublished":"boolean","lastSavedWhen":"Date","name":"string","ownerId":"number","previousId":"number","regionId":"string","scoreTotal":"number"}, {"createdWhen":"CURRENT_TIMESTAMP","isEducational":"false","isPublished":"false","lastSavedWhen":"CURRENT_TIMESTAMP","previousId":null,"regionId":"MAIN"}))
				return null;

			var foreignKeyNames = ["ownerId","previousId","regionId"];
			var vo = new cuboro.tables.TrackVO();
			var copyFields = ["createdWhen","data","id","imageUrl","isEducational","isPublished","lastSavedWhen","name","ownerId","previousId","regionId","scoreTotal"];
			for (var i = 0; i < copyFields.length; ++i)
			{
				vo[copyFields[i]] = raw[copyFields[i]];
				if (!vo[copyFields[i]] && kr3m.util.Util.contains(foreignKeyNames, copyFields[i]))
					vo[copyFields[i]] = null;
			}
			return vo;
		}



		public constructor(rawData?:any)
		{
			if (rawData)
			{
				for (var i in rawData)
				{
					if (cuboro.tables.TrackVO.isColumnName(i))
						this[i] = rawData[i];
				}
			}
		}



		private wrapErrorCallback(
			errorCallback:ErrorCallback,
			functionName:string):ErrorCallback
		{
			if (!errorCallback)
				return errorCallback;

			var newCallback = (errorMessage) =>
			{
				errorCallback("cuboro.tables.TrackVO." + functionName + " - " + errorMessage);
			}
			return newCallback;
		}



		/*
			Will be called after the class was created and filled
			with content from the database.
		*/
		public postLoad():void
		{
			var autoUpdateFields = ["lastSavedWhen"];
			var oldValues:{[field:string]:Date} = {};
			for (var i = 0; i < autoUpdateFields.length; ++i)
			{
				var field = autoUpdateFields[i];
				oldValues[field] = this[field];
			}
			Object.defineProperty(this, "__oldAutoUpdateFieldValues", {value : oldValues, enumerable : false});
		}



		/*
			Will be called before the class' content will be
			written into the database.
		*/
		public preStore():void
		{
			var autoUpdateFields = ["lastSavedWhen"];

			if (!this["__oldAutoUpdateFieldValues"])
				Object.defineProperty(this, "__oldAutoUpdateFieldValues", {value : {}, enumerable : false});

			for (var i = 0; i < autoUpdateFields.length; ++i)
			{
				var field = autoUpdateFields[i];
				if (this[field] == this["__oldAutoUpdateFieldValues"][field])
					delete this[field];
				else
					this["__oldAutoUpdateFieldValues"][field] = this[field];
			}
		}



		/*
			Will be called after the class' content was
			written into the database.
		*/
		public postStore():void
		{
			var autoUpdateFields = ["lastSavedWhen"];
			for (var i = 0; i < autoUpdateFields.length; ++i)
			{
				var field = autoUpdateFields[i];
				this[field] = this["__oldAutoUpdateFieldValues"][field];
			}
		}



		public insert(
			callback?:(insertedId:number) => void,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "insert");
			this.preStore();
			db.insert("tracks", this, (insertedId:number) =>
			{
				this.id = insertedId;
				this.postStore();
				callback && callback(insertedId);
			}, errorCallback);
		}



		public upsert(
			callback?:(insertedId:number) => void,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "upsert");
			this.preStore();
			db.upsert("tracks", this, (insertedId:number) =>
			{
				this.id = insertedId || this.id;
				this.postStore();
				callback && callback(insertedId);
			}, null, errorCallback);
		}



		public update(
			callback?:Callback,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "update");
			this.preStore();
			db.update("tracks", this, () =>
			{
				this.postStore();
				callback && callback();
			}, "id", errorCallback);
		}



		public delete(
			callback?:Callback,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "delete");
			var where = db.escape("id = ?", [this.id]);
			db.deleteBatch("tracks", where, callback, errorCallback);
		}



		public getOwner(
			callback:CB<cuboro.tables.UserVO>,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "getOwner");
			var sql = "SELECT * FROM `users` WHERE `id` = ? LIMIT 0,1";
			sql = db.escape(sql, [this.ownerId]);
			db.fetchRow(sql, (data) =>
			{
				if (!data)
					return callback(undefined);

				data.__proto__ = kr3m.util.Factory.getInstance().map(cuboro.tables.UserVO).prototype;
				data.postLoad();
				callback(data);
			}, errorCallback);
		}



		public getPrevious(
			callback:CB<cuboro.tables.TrackVO>,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "getPrevious");
			var sql = "SELECT * FROM `tracks` WHERE `id` = ? LIMIT 0,1";
			sql = db.escape(sql, [this.previousId]);
			db.fetchRow(sql, (data) =>
			{
				if (!data)
					return callback(undefined);

				data.__proto__ = kr3m.util.Factory.getInstance().map(cuboro.tables.TrackVO).prototype;
				data.postLoad();
				callback(data);
			}, errorCallback);
		}



		public getRegion(
			callback:CB<cuboro.tables.RegionVariantVO>,
			errorCallback?:ErrorCallback):void
		{
			errorCallback = this.wrapErrorCallback(errorCallback, "getRegion");
			var sql = "SELECT * FROM `region_variants` WHERE `id` = ? LIMIT 0,1";
			sql = db.escape(sql, [this.regionId]);
			db.fetchRow(sql, (data) =>
			{
				if (!data)
					return callback(undefined);

				data.__proto__ = kr3m.util.Factory.getInstance().map(cuboro.tables.RegionVariantVO).prototype;
				data.postLoad();
				callback(data);
			}, errorCallback);
		}



		public getComments(
			where:string|{[colName:string]:any},
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.CommentVO[]>,
			errorCallback:ErrorCallback):void;

		public getComments(
			where:string|{[colName:string]:any},
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.CommentVO[]>):void;

		public getComments(
			where:string|{[colName:string]:any},
			callback:CB<cuboro.tables.CommentVO[]>,
			errorCallback:ErrorCallback):void;

		public getComments(
			where:string|{[colName:string]:any},
			callback:CB<cuboro.tables.CommentVO[]>):void;

		public getComments(
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.CommentVO[]>,
			errorCallback:ErrorCallback):void;

		public getComments(
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.CommentVO[]>):void;

		public getComments(
			callback:CB<cuboro.tables.CommentVO[]>,
			errorCallback:ErrorCallback):void;

		public getComments(
			callback:CB<cuboro.tables.CommentVO[]>):void;

		public getComments():void
		{
			var u = kr3m.util.Util;


			var whereObj = <{[colName:string]:any}> u.getFirstOfType(arguments, "object", 0, 0);
			var whereString = whereObj ? db.where(whereObj) : <string> u.getFirstOfType(arguments, "string", 0, 0);
			var where = whereString ? " AND (" + whereString.replace(/\bWHERE\b/i, "") + ") " : "";

			var offset = <number> u.getFirstOfType(arguments, "number", 0, 0);
			var limit = <number> u.getFirstOfType(arguments, "number", 0, 1);
			var limits = (offset !== undefined && limit !== undefined) ? db.escape(" LIMIT ?, ?", [offset, limit]) : "";

			var callback = <CB<cuboro.tables.CommentVO[]>> u.getFirstOfType(arguments, "function", 0, 0);
			var errorCallback = <ErrorCallback> u.getFirstOfType(arguments, "function", 0, 1);
			errorCallback = this.wrapErrorCallback(errorCallback, "getComments");

			var sql = "SELECT * FROM `comments` WHERE `trackId` = ? " + where + limits;
			sql = db.escape(sql, [this.id]);
			db.fetchAll(sql, (rows) =>
			{
				for (var i = 0; i < rows.length; ++i)
				{
					rows[i].__proto__ = kr3m.util.Factory.getInstance().map(cuboro.tables.CommentVO).prototype;
					rows[i].postLoad();
				}
				callback(rows);
			}, errorCallback);
		}



		public getCompetitions(
			where:string|{[colName:string]:any},
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.CompetitionVO[]>,
			errorCallback:ErrorCallback):void;

		public getCompetitions(
			where:string|{[colName:string]:any},
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.CompetitionVO[]>):void;

		public getCompetitions(
			where:string|{[colName:string]:any},
			callback:CB<cuboro.tables.CompetitionVO[]>,
			errorCallback:ErrorCallback):void;

		public getCompetitions(
			where:string|{[colName:string]:any},
			callback:CB<cuboro.tables.CompetitionVO[]>):void;

		public getCompetitions(
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.CompetitionVO[]>,
			errorCallback:ErrorCallback):void;

		public getCompetitions(
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.CompetitionVO[]>):void;

		public getCompetitions(
			callback:CB<cuboro.tables.CompetitionVO[]>,
			errorCallback:ErrorCallback):void;

		public getCompetitions(
			callback:CB<cuboro.tables.CompetitionVO[]>):void;

		public getCompetitions():void
		{
			var u = kr3m.util.Util;


			var whereObj = <{[colName:string]:any}> u.getFirstOfType(arguments, "object", 0, 0);
			var whereString = whereObj ? db.where(whereObj) : <string> u.getFirstOfType(arguments, "string", 0, 0);
			var where = whereString ? " AND (" + whereString.replace(/\bWHERE\b/i, "") + ") " : "";

			var offset = <number> u.getFirstOfType(arguments, "number", 0, 0);
			var limit = <number> u.getFirstOfType(arguments, "number", 0, 1);
			var limits = (offset !== undefined && limit !== undefined) ? db.escape(" LIMIT ?, ?", [offset, limit]) : "";

			var callback = <CB<cuboro.tables.CompetitionVO[]>> u.getFirstOfType(arguments, "function", 0, 0);
			var errorCallback = <ErrorCallback> u.getFirstOfType(arguments, "function", 0, 1);
			errorCallback = this.wrapErrorCallback(errorCallback, "getCompetitions");

			var sql = "SELECT * FROM `competitions` WHERE `baseTrackId` = ? " + where + limits;
			sql = db.escape(sql, [this.id]);
			db.fetchAll(sql, (rows) =>
			{
				for (var i = 0; i < rows.length; ++i)
				{
					rows[i].__proto__ = kr3m.util.Factory.getInstance().map(cuboro.tables.CompetitionVO).prototype;
					rows[i].postLoad();
				}
				callback(rows);
			}, errorCallback);
		}



		public getTracks(
			where:string|{[colName:string]:any},
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.TrackVO[]>,
			errorCallback:ErrorCallback):void;

		public getTracks(
			where:string|{[colName:string]:any},
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.TrackVO[]>):void;

		public getTracks(
			where:string|{[colName:string]:any},
			callback:CB<cuboro.tables.TrackVO[]>,
			errorCallback:ErrorCallback):void;

		public getTracks(
			where:string|{[colName:string]:any},
			callback:CB<cuboro.tables.TrackVO[]>):void;

		public getTracks(
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.TrackVO[]>,
			errorCallback:ErrorCallback):void;

		public getTracks(
			offset:number,
			limit:number,
			callback:CB<cuboro.tables.TrackVO[]>):void;

		public getTracks(
			callback:CB<cuboro.tables.TrackVO[]>,
			errorCallback:ErrorCallback):void;

		public getTracks(
			callback:CB<cuboro.tables.TrackVO[]>):void;

		public getTracks():void
		{
			var u = kr3m.util.Util;


			var whereObj = <{[colName:string]:any}> u.getFirstOfType(arguments, "object", 0, 0);
			var whereString = whereObj ? db.where(whereObj) : <string> u.getFirstOfType(arguments, "string", 0, 0);
			var where = whereString ? " AND (" + whereString.replace(/\bWHERE\b/i, "") + ") " : "";

			var offset = <number> u.getFirstOfType(arguments, "number", 0, 0);
			var limit = <number> u.getFirstOfType(arguments, "number", 0, 1);
			var limits = (offset !== undefined && limit !== undefined) ? db.escape(" LIMIT ?, ?", [offset, limit]) : "";

			var callback = <CB<cuboro.tables.TrackVO[]>> u.getFirstOfType(arguments, "function", 0, 0);
			var errorCallback = <ErrorCallback> u.getFirstOfType(arguments, "function", 0, 1);
			errorCallback = this.wrapErrorCallback(errorCallback, "getTracks");

			var sql = "SELECT * FROM `tracks` WHERE `previousId` = ? " + where + limits;
			sql = db.escape(sql, [this.id]);
			db.fetchAll(sql, (rows) =>
			{
				for (var i = 0; i < rows.length; ++i)
				{
					rows[i].__proto__ = kr3m.util.Factory.getInstance().map(cuboro.tables.TrackVO).prototype;
					rows[i].postLoad();
				}
				callback(rows);
			}, errorCallback);
		}

//# /!CLIENT
	}
}
