/*
	This file was automatically created using a source code generator.
	Do not edit this file manually as all changes will be overwritten
	the next time the generator runs again.
*/



module cuboro.tables
{
	export class TrackVO
	{
		public static DATA_MAX_LENGTH = 4294967295;
		public static DATA_MAX_LENGTH_SECURE = 2147483647;

		public static IMAGE_URL_MAX_LENGTH = 65535;
		public static IMAGE_URL_MAX_LENGTH_SECURE = 32767;

		public static NAME_MAX_LENGTH = 200;
		public static NAME_MAX_LENGTH_SECURE = 100;

		public static REGION_ID_MAX_LENGTH = 32;
		public static REGION_ID_MAX_LENGTH_SECURE = 16;
	}
}
