/*
	This file was automatically created using a source code generator.
	Do not edit this file manually as all changes will be overwritten
	the next time the generator runs again.
*/



module cuboro.tables
{
	export class UserVO
	{
		public static IMAGE_URL_MAX_LENGTH = 500;
		public static IMAGE_URL_MAX_LENGTH_SECURE = 250;

		public static LAST_REGION_ID_MAX_LENGTH = 32;
		public static LAST_REGION_ID_MAX_LENGTH_SECURE = 16;

		public static NAME_MAX_LENGTH = 200;
		public static NAME_MAX_LENGTH_SECURE = 100;
	}
}
