module kr3m
{
	export const TRANSACTION_STATUS_PENDING = "PENDING";
	export const TRANSACTION_STATUS_SETTLED = "SETTLED";
	export const TRANSACTION_STATUS_CANCELLED = "CANCELLED";
	export const TRANSACTION_STATUS_CONTESTED = "CONTESTED";
}
